### ISSUE TITLE
NPE in IDEA plugin while editing

### ISSUE THREAD

**Issue by Abnaxos** [Abnaxos/meldioc#40]
While editing, sometimes an NPE occurs in the IDEA plugin. An example of such an NPE:

```
java.lang.NullPointerException
	at ch.raffael.compose.idea.IdeaAdaptor.lambda$loadConfigurations$24(IdeaAdaptor.java:334)
	at io.vavr.control.Option.filter(Option.java:366)
	at ch.raffael.compose.idea.IdeaAdaptor.loadConfigurations(IdeaAdaptor.java:334)
	at ch.raffael.compose.idea.IdeaAdaptor.commonElement(IdeaAdaptor.java:299)
	at ch.raffael.compose.idea.IdeaAdaptor.methodElement(IdeaAdaptor.java:259)
	at ch.raffael.compose.idea.IdeaAdaptor.lambda$declaredMethods$9(IdeaAdaptor.java:184)
	at io.vavr.collection.List.map(List.java:1038)
	at io.vavr.collection.List.map(List.java:128)
	at ch.raffael.compose.idea.IdeaAdaptor.lambda$declaredMethods$1b94ae6e$1(IdeaAdaptor.java:184)
	at io.vavr.Tuple3.apply(Tuple3.java:269)
	at ch.raffael.compose.idea.IdeaAdaptor.lambda$declaredMethods$10(IdeaAdaptor.java:182)
	at io.vavr.control.Option.map(Option.java:392)
	at ch.raffael.compose.idea.IdeaAdaptor.declaredMethods(IdeaAdaptor.java:182)
	at ch.raffael.compose.idea.IdeaAdaptor.declaredMethods(IdeaAdaptor.java:81)
	at ch.raffael.compose.model.ModelType.<init>(ModelType.java:102)
	at ch.raffael.compose.model.Model.lambda$modelOf$8(Model.java:113)
	at io.vavr.Tuple2.apply(Tuple2.java:238)
	at ch.raffael.compose.model.Model.modelOf(Model.java:103)
	at ch.raffael.compose.idea.Context.inspect(Context.java:62)
	at ch.raffael.compose.idea.AbstractComposeInspection.inspect(AbstractComposeInspection.java:182)
	at ch.raffael.compose.idea.AbstractComposeInspection$3.visitMethod(AbstractComposeInspection.java:233)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:273)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

There could also be other instances – while editing, there may be very uncommon situations in very incomplete code.

**Comment by Abnaxos** [comment]
Found more such issues: all annotation values need to be prepared handled as nullable, as this can happen during editing, even if a default is set.

**Comment by Abnaxos** [comment]
This specific instance is fixed. Open specific issues when new such issues come up.
